name: Cleanup Old Images
on:
  schedule:
    - cron: '0 0 * * 0' 
  workflow_dispatch:

jobs:
  delete-older-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v3.0.0
        with:
          image-names: go-home
          cut-off: 4w
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-tags: pr* sha* !v* !latest